spring.application.name=demo


spring.datasource.url=jdbc:mysql://localhost:3306/english
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update


spring.main.allow-circular-references=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phucp9698@gmail.com
spring.mail.password=lolftkugkckkiwul

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf template configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.mail.default-encoding=UTF-8
jwt.secret=Z3dlMTIzNDU2Nzg5YWJjZGVmZ2hpamtsbW5vcHFyc3Q=

firebase.service-account-file=firebase/englishhub-9f038-firebase-adminsdk-fbsvc-904d9f8322.json


payos.client-id=e1144c18-70a5-4a90-99b6-c2b632202d66
payos.api-key=5f98787a-64dd-4a07-a298-34f0760c7092
payos.checksum-key=91b37ca6dc65d4f33831622726430fec9bf6dbd7dc31d7c3954a6b4b0f3955d5






